# GitHub Secret Scanning configuration
# This helps prevent committing secrets to the repository

# Patterns to detect common secrets
patterns:
  - name: "API Keys"
    pattern: '(?i)(api[_-]?key|apikey)\s*[:=]\s*["\']?([a-zA-Z0-9]{20,})["\']?'
  
  - name: "AWS Keys"
    pattern: 'AKIA[0-9A-Z]{16}'
  
  - name: "GitHub Tokens"
    pattern: 'ghp_[a-zA-Z0-9]{36}|gho_[a-zA-Z0-9]{36}|ghu_[a-zA-Z0-9]{36}|ghs_[a-zA-Z0-9]{36}|ghr_[a-zA-Z0-9]{36}'
  
  - name: "Private Keys"
    pattern: '-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----'
  
  - name: "Database Credentials"
    pattern: '(?i)(database|db)[_-]?(password|pass|pwd)\s*[:=]\s*["\']?([^\s"\']{8,})["\']?'
  
  - name: "JWT Tokens"
    pattern: 'eyJ[A-Za-z0-9-_=]+\.eyJ[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'

