name: Compatibility Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'composer.json'
      - 'composer.lock'
      - '.compatibility.yml'
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM

jobs:
  compatibility-tests:
    name: PHP Compatibility Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, curl, json
          coverage: none
      
      - name: Install Composer
        uses: php-actions/composer@v1
        with:
          command: install
          args: --no-interaction --prefer-dist
      
      - name: Run compatibility tests
        run: vendor/bin/compatibility-tester test --php=${{ matrix.php-version }}
      
      - name: Generate report
        run: vendor/bin/compatibility-tester report --format=markdown --output=compatibility-report.md
        continue-on-error: true
      
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: compatibility-report-php-${{ matrix.php-version }}
          path: compatibility-report.md

